# Generated by Django 5.2.16 on 2026-07-21 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_component', models.CharField(choices=[('whole_blood', 'Whole Blood'), ('red_cells', 'Red Blood Cells'), ('platelets', 'Platelets'), ('plasma', 'Plasma'), ('cryoprecipitate', 'Cryoprecipitate')], default='whole_blood', max_length=30)),
                ('units_required', models.PositiveIntegerField(default=1)),
                ('required_date', models.DateField()),
                ('urgency_level', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('hospital_or_blood_bank', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('additional_details', models.TextField(blank=True)),
                ('medical_document', models.FileField(blank=True, null=True, upload_to='blood_requests/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matching', 'Matching Donors'), ('matched', 'Donor Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
