# Generated by Django 6.0 on 2026-07-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient'), ('patient', 'Patient'), ('hospital', 'Hospital')], default='donor', max_length=10),
        ),
    ]
