# Generated by Django 5.2.16 on 2026-07-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('accounts', '0002_user_blood_group'),
    ]

    operations = [
    ]
